image: gitpod/workspace-full-vnc

tasks:
  - name: Install
    init: |
      poetry install
      npx --yes playwright install-deps
      gp sync-done poetry
  - name: Install Playwright Deps
    init: gp sync-await poetry
    command: poetry run rfbrowser init
  - name: Run Ollama in Docker
    init: gp sync-await poetry
    command: |
      docker run -d -v ollama:/root/.ollama -p 11434:11434 --name ollama ollama/ollama
      docker exec -it ollama ollama run phi4
ports:
  - port: 6080
    onOpen: open-preview
vscode:
  extensions:
    - ms-python.python
    - d-biehl.robotcode
    - ms-azuretools.vscode-docker