site_name: Robot Framework Heal
repo_url: https://github.com/manykarim/robotframework-heal
repo_name: robotframework-heal
theme:
  name: material
  palette:
    scheme: slate
  features:
    - content.code.copy
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format